### ISSUE TITLE
Rod randomly retracts with no reason.

### ISSUE THREAD

**Issue by SpadeCA** [North-West-Wind/forge-autofish#4]
**Describe the bug**
AFK fishing isn't possible because the rod seems to be getting reeled back in, even when there is no fish, and it seems the mod also doesn't realize this cause it doesn't recast. Also doesn't play the reel sound either when it happens. Tried adjusting recast delay to 1000ms but seems to make zero difference.

**To Reproduce**
Run the auto fisher for more than a couple catches, sometimes happens after first cast, sometimes not. I could watch this happen 4-5 times in a few minutes, so much so, I chose to rather just fish manually.

**Expected behavior**
AFK fishing.

**Screenshots**
I could get a video but seems pointless with the reproduction rate.

**Version**
Latest version(1.1.3) on MC 1.16.4, also in Singleplayer.

**Comment by SpadeCA** [comment]
**Video** 
https://user-images.githubusercontent.com/11309486/103161269-059f7400-4794-11eb-89e3-fd69cccc4508.mp4

**Comment by North-West-Wind** [comment]
This should be fixed in the latest update. (2.0.0)

**Comment by SpadeCA** [comment]
Issue is not fixed. 

![image](https://user-images.githubusercontent.com/11309486/103329270-e5c8b400-4a10-11eb-9c05-e778fae9eab2.png)

This is after 7 minutes of fishing, same issue.

**Comment by Drunkender** [comment]
I also get this with mod version 2.0.0. Cast rod sometimes autofishes sometimes pulls reel with nothing and doesn't recast.

**Comment by North-West-Wind** [comment]
Alright, I will take a deeper look into this.

The funny thing is that I've never encountered this issue in my test world.

**Comment by North-West-Wind** [comment]
@SpadeCA @Drunkender Do you both have rod protect enabled? If not, I won't have to investigate it.

**Comment by SpadeCA** [comment]
Reset my config to be sure but yes rod protect is on by default. 
![image](https://user-images.githubusercontent.com/11309486/103484733-f6c54c80-4da5-11eb-98c5-39ba414aed81.png)
Turning it off doesn't fix the issue.

**Comment by North-West-Wind** [comment]
Thanks for telling me that.
